# Generated by Django 4.1.7 on 2023-04-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repeatabletransaction",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("ANNUALLY", "Annually"),
                ],
                default="DAILY",
                max_length=10,
            ),
        ),
    ]
