# Generated by Django 4.1.7 on 2023-03-25 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="transactions",
            name="execution_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="is_executed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RepeatableTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("num_occurrences", models.IntegerField(default=1)),
                ("frequency_days", models.IntegerField(default=1)),
                (
                    "frequency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.categories",
                    ),
                ),
            ],
        ),
    ]
