# Generated by Django 4.1.7 on 2023-03-25 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planner", "0002_frequencies_transactions_execution_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repeatabletransactions",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.categories",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repeatabletransactions",
            name="transaction_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.types",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repeatabletransactions",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repeatabletransactions",
            name="frequency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.frequencies"
            ),
        ),
    ]
