# Generated by Django 4.1.7 on 2023-03-26 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planner", "0004_transactions_repeatable_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budgets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="repeatabletransactions",
            old_name="frequency_days",
            new_name="recurrence_value",
        ),
        migrations.RenameField(
            model_name="repeatabletransactions",
            old_name="transaction_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="transactions",
            old_name="transaction_type",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="repeatabletransactions",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="repeatabletransactions",
            name="num_occurrences",
        ),
        migrations.AddField(
            model_name="repeatabletransactions",
            name="base_amout",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repeatabletransactions",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("QUATERLY", "Quaterly"),
                    ("ANNUALLY", "Annually"),
                ],
                default="DAILY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="repeatable_transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.repeatabletransactions",
            ),
        ),
        migrations.DeleteModel(
            name="Frequencies",
        ),
        migrations.AddField(
            model_name="repeatabletransactions",
            name="budget",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.budgets",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactions",
            name="budget",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.budgets",
            ),
            preserve_default=False,
        ),
    ]
