# Generated by Django 4.1.7 on 2023-03-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0005_budgets_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="is_repatable",
        ),
        migrations.AlterField(
            model_name="repeatabletransactions",
            name="budget",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.budgets",
            ),
        ),
        migrations.AlterField(
            model_name="repeatabletransactions",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.categories",
            ),
        ),
        migrations.AlterField(
            model_name="repeatabletransactions",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.types",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.categories",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.types",
            ),
        ),
    ]
