# Generated by Django 4.1.7 on 2023-03-27 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0008_alter_budget_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="execution_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
