# Generated by Django 4.1.7 on 2023-03-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0009_alter_transaction_execution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="repeatable_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.repeatabletransaction",
            ),
        ),
    ]
