# Generated by Django 4.1.7 on 2023-03-28 21:46

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0011_budget_amount_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="PLN",
                max_digits=10,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="repeatabletransaction",
            name="base_amout",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="PLN",
                max_digits=10,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="PLN",
                max_digits=10,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
    ]
