# Generated by Django 4.1.7 on 2023-04-05 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planner", "0012_alter_budget_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="sers",
            field=models.ManyToManyField(
                through="planner.UserCategory", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
