# Generated by Django 4.1.7 on 2023-04-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("planner", "0014_alter_usercategory_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercategory",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usercategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="usercategory",
            name="user",
        ),
        migrations.AlterField(
            model_name="repeatabletransaction",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="repeatabletransaction",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.type",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
        migrations.DeleteModel(
            name="UserCategory",
        ),
    ]
