# Generated by Django 4.1.7 on 2023-04-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
        ("planner", "0015_alter_usercategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repeatabletransaction",
            name="budget",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="budgets.budget",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgets.budget"
            ),
        ),
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
